<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0T3LLVM" failures="1" tests="5" name="TestNGProject" time="104.275" errors="0" timestamp="2023-02-16T20:34:16 EST">
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="23.87"/>
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="10.777"/>
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="10.548"/>
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="25.842">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.class05._02_HW_AddEmployee.addEmployeeTest(_02_HW_AddEmployee.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="10.015"/>
</testsuite> <!-- TestNGProject -->
